### ISSUE TITLE
add footer with creators gitbuh links

### ISSUE THREAD

**Issue by shaynefw** [jjocelynn/WikiGo#50]

**Comment by shaynefw** [comment]
```html
<footer>
        <div class="github-logos">
            <a href="https://github.com/Ishaval" target="_blank">
              <img src="https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png" alt="Github logo" class="github-logo">
              <p class="github-username">Ishaval</p>
            </a>
            <a href="https://github.com/jjocelynn" target="_blank">
              <img src="https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png" alt="Github logo" class="github-logo">
              <p class="github-username">jjocelynn</p>
            </a>
            <a href="https://github.com/shaynefw" target="_blank">
              <img src="https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png" alt="Github logo" class="github-logo">
              <p class="github-username">shaynefw</p>
            </a>
          </div>
    </footer>
```
```css
footer {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 50px;
  background-color: #333;
  color: #fff;
}

.github-logos {
  display: flex;
  justify-content: center;
  align-items: center;
}

.github-logo {
  width: 50px;
  height: 50px;
  margin-right: 10px;
}

.github-username {
  display: none;
}

a:hover .github-username {
  display: block;
  color: rgb(0, 234, 255);
  background-color: black;
}
```
