### ISSUE TITLE
change background colour to match background image

### ISSUE THREAD

**Issue by shaynefw** [jjocelynn/WikiGo#68]

**Comment by shaynefw** [comment]
```css
body {
  background-image: url("./giphy.gif");
  background-size: 40em;
  background-position-x: center;
  background-repeat: no-repeat;
  background-color: #061113; /*added this line*/
  color: white;
}
```
